name: Update CSS Battle Solutions

on:
  repository_dispatch:
    types: [cssbattle-update]  # Matches your event_type
  workflow_dispatch: # Manual trigger option

jobs:
  update-solutions:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout Astro site
      uses: actions/checkout@v4
      with:
        token: ${{ secrets.GITHUB_TOKEN }}
        
    - name: Setup Go
      uses: actions/setup-go@v4
      with:
        go-version: '1.21'
        
    - name: Install Go dependencies
      run: |
        cd scripts
        go mod download
        
    - name: Run CSS Battle sync
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        GITHUB_OWNER: dcotelessa
        GITHUB_REPO: cssbattle-solutions
      run: |
        cd scripts
        go run cssbattle-sync.go
        
    - name: Setup Node.js
      uses: actions/setup-node@v4
      with:
        node-version: '18'
        
    - name: Install Astro dependencies
      run: npm install
      
    - name: Build Astro site
      run: npm run build
      
    - name: Commit and push changes
      run: |
        git config --local user.email "action@github.com"
        git config --local user.name "GitHub Action"
        git add .
        if git diff --staged --quiet; then
          echo "No changes to commit"
        else
          git commit -m "Update CSS Battle solutions - $(date)"
          git push
        fi
